FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -q \
    && apt-get install -qy \
        # install python \
        python3-pip python3-dev \
        # install go \
        golang \
        # install rust \
        rustc cargo \
        # nodejs \
        nodejs npm \
        # latex \
        texlive-full \
        # other tools \
        gnuplot make \
    && ln -s /usr/bin/python3 /usr/bin/python \
    && ln -s /usr/bin/pip3 /usr/bin/pip \
    && rm -rf /var/lib/apt/lists/*
