
latex:
	docker build --tag latex:ubuntu20.08 -f latex-dockerfile .

nodejs:
	docker build --tag nodejs:centos8 -f nodejs-dockerfile .

tool:
	docker build --tag tool:ubuntu20.08 -f tool-dockerfile .

